// This file is auto-generated by @hey-api/openapi-ts

export const Body_gwy_upload_chat_attachmentsSchema = {
    properties: {
        files: {
            items: {
                type: 'string',
                format: 'binary'
            },
            type: 'array',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['files'],
    title: 'Body_gwy-upload_chat_attachments'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChatAttachmentListResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChatAttachmentResponse'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ChatAttachmentListResponse'
} as const;

export const ChatAttachmentResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        file_name: {
            type: 'string',
            title: 'File Name'
        },
        original_name: {
            type: 'string',
            title: 'Original Name'
        },
        attachment_type: {
            type: 'string',
            title: 'Attachment Type'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        file_path: {
            type: 'string',
            title: 'File Path'
        },
        size_bytes: {
            type: 'integer',
            title: 'Size Bytes'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        extracted_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extracted Text'
        },
        extraction_status: {
            type: 'string',
            title: 'Extraction Status'
        },
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'file_name', 'original_name', 'attachment_type', 'mime_type', 'file_path', 'size_bytes', 'extraction_status'],
    title: 'ChatAttachmentResponse'
} as const;

export const ChatMessageListResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChatMessageResponse'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ChatMessageListResponse'
} as const;

export const ChatMessageResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        intent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intent'
        },
        historical_reference: {
            type: 'boolean',
            title: 'Historical Reference',
            default: false
        },
        citations: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Citations'
        },
        retrieval_trace: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Retrieval Trace'
        },
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'role', 'content'],
    title: 'ChatMessageResponse'
} as const;

export const ChatRequestBaseSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        year: {
            type: 'integer',
            title: 'Year',
            default: 2026
        },
        exam_type: {
            type: 'string',
            title: 'Exam Type',
            default: 'national'
        },
        doc_group: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc Group'
        },
        doc_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc Type'
        },
        top_k: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Top K',
            default: 6
        },
        use_rerank: {
            type: 'boolean',
            title: 'Use Rerank',
            default: true
        },
        mode: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['policy_rag', 'position_recommendation']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mode'
        },
        intent_hint: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intent Hint'
        },
        position_profile: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PositionRecommendationProfile'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['query'],
    title: 'ChatRequestBase'
} as const;

export const ChatSessionCreateRequestSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    type: 'object',
    title: 'ChatSessionCreateRequest'
} as const;

export const ChatSessionListResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChatSessionResponse'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ChatSessionListResponse'
} as const;

export const ChatSessionResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        last_intent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Intent'
        },
        active_topic: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Active Topic'
        },
        mentioned_docs: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Mentioned Docs'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        summary_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary Updated At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'title'],
    title: 'ChatSessionResponse'
} as const;

export const ChunkDebugListResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChunkDebugRecord'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ChunkDebugListResponse'
} as const;

export const ChunkDebugRecordSchema = {
    properties: {
        chunk_id: {
            type: 'string',
            title: 'Chunk Id'
        },
        source_file: {
            type: 'string',
            title: 'Source File'
        },
        doc_group: {
            type: 'string',
            title: 'Doc Group'
        },
        doc_type: {
            type: 'string',
            title: 'Doc Type'
        },
        chunk_type: {
            type: 'string',
            title: 'Chunk Type'
        },
        section: {
            type: 'string',
            title: 'Section'
        },
        question: {
            type: 'string',
            title: 'Question'
        },
        page_start: {
            type: 'integer',
            title: 'Page Start'
        },
        page_end: {
            type: 'integer',
            title: 'Page End'
        },
        char_count: {
            type: 'integer',
            title: 'Char Count'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata'
        }
    },
    type: 'object',
    required: ['chunk_id', 'source_file', 'doc_group', 'doc_type', 'chunk_type', 'section', 'question', 'page_start', 'page_end', 'char_count', 'content'],
    title: 'ChunkDebugRecord'
} as const;

export const ChunkDebugStatsResponseSchema = {
    properties: {
        source_file: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source File'
        },
        doc_group: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc Group'
        },
        doc_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc Type'
        },
        total_chunks: {
            type: 'integer',
            title: 'Total Chunks'
        },
        chunk_type_count: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Chunk Type Count'
        },
        avg_char_count: {
            type: 'number',
            title: 'Avg Char Count'
        },
        min_char_count: {
            type: 'integer',
            title: 'Min Char Count'
        },
        max_char_count: {
            type: 'integer',
            title: 'Max Char Count'
        },
        missing_question_count: {
            type: 'integer',
            title: 'Missing Question Count'
        },
        missing_section_count: {
            type: 'integer',
            title: 'Missing Section Count'
        },
        missing_page_count: {
            type: 'integer',
            title: 'Missing Page Count'
        },
        fallback_count: {
            type: 'integer',
            title: 'Fallback Count',
            default: 0
        },
        fallback_ratio: {
            type: 'number',
            title: 'Fallback Ratio'
        }
    },
    type: 'object',
    required: ['total_chunks', 'chunk_type_count', 'avg_char_count', 'min_char_count', 'max_char_count', 'missing_question_count', 'missing_section_count', 'missing_page_count', 'fallback_ratio'],
    title: 'ChunkDebugStatsResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PolicyImportRequestSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        owner_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner User Id'
        },
        collection_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Collection Name'
        }
    },
    type: 'object',
    required: ['path'],
    title: 'PolicyImportRequest'
} as const;

export const PolicyImportResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        file_count: {
            type: 'integer',
            title: 'File Count'
        },
        chunk_count: {
            type: 'integer',
            title: 'Chunk Count'
        },
        failed_files: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Failed Files'
        },
        chunk_stats: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chunk Stats'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        },
        debug_artifacts: {
            additionalProperties: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'null'
                    }
                ]
            },
            type: 'object',
            title: 'Debug Artifacts'
        },
        layout_stats: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Layout Stats'
        }
    },
    type: 'object',
    required: ['success', 'file_count', 'chunk_count', 'failed_files'],
    title: 'PolicyImportResponse'
} as const;

export const PolicyQueryRequestSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        session_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Session Id'
        },
        year: {
            type: 'integer',
            title: 'Year',
            default: 2026
        },
        exam_type: {
            type: 'string',
            title: 'Exam Type',
            default: 'national'
        },
        doc_group: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc Group'
        },
        doc_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc Type'
        },
        top_k: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Top K',
            default: 6
        },
        use_rerank: {
            type: 'boolean',
            title: 'Use Rerank',
            default: true
        },
        mode: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['policy_rag', 'position_recommendation']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mode'
        },
        intent_hint: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intent Hint'
        },
        position_profile: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PositionRecommendationProfile'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['query'],
    title: 'PolicyQueryRequest'
} as const;

export const PolicyQueryResponseSchema = {
    properties: {
        answer: {
            type: 'string',
            title: 'Answer'
        },
        intent: {
            type: 'string',
            title: 'Intent'
        },
        need_rag: {
            type: 'boolean',
            title: 'Need Rag'
        },
        decision_branch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Decision Branch'
        },
        citations: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Citations'
        },
        retrieval_trace: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Retrieval Trace'
        },
        rewritten_queries: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Rewritten Queries'
        },
        metadata_filter: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata Filter'
        },
        rerank_results: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Rerank Results'
        },
        recommendations: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Recommendations'
        },
        risk_review: {
            additionalProperties: true,
            type: 'object',
            title: 'Risk Review'
        },
        report: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Report'
        },
        need_more_info: {
            type: 'boolean',
            title: 'Need More Info',
            default: false
        },
        missing_fields: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Missing Fields'
        },
        recommendation_task_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommendation Task Id'
        },
        historical_reference: {
            type: 'boolean',
            title: 'Historical Reference',
            default: false
        },
        session: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ChatSessionResponse'
                },
                {
                    type: 'null'
                }
            ]
        },
        user_message: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ChatMessageResponse'
                },
                {
                    type: 'null'
                }
            ]
        },
        assistant_message: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ChatMessageResponse'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['answer', 'intent', 'need_rag', 'citations', 'retrieval_trace', 'rewritten_queries', 'rerank_results'],
    title: 'PolicyQueryResponse'
} as const;

export const PolicySearchRequestSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        year: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year'
        },
        exam_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Exam Type'
        },
        doc_group: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc Group'
        },
        top_k: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Top K',
            default: 5
        },
        use_rerank: {
            type: 'boolean',
            title: 'Use Rerank',
            default: true
        }
    },
    type: 'object',
    required: ['query'],
    title: 'PolicySearchRequest'
} as const;

export const PolicySearchResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/PolicySearchResult'
            },
            type: 'array',
            title: 'Results'
        }
    },
    type: 'object',
    required: ['results'],
    title: 'PolicySearchResponse'
} as const;

export const PolicySearchResultSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        score: {
            type: 'number',
            title: 'Score'
        },
        rerank_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rerank Score'
        },
        metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata'
        }
    },
    type: 'object',
    required: ['content', 'score'],
    title: 'PolicySearchResult'
} as const;

export const PositionAnalysisReportResponseSchema = {
    properties: {
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        stage: {
            type: 'string',
            title: 'Stage'
        },
        report: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Report'
        },
        report_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Report Text'
        }
    },
    type: 'object',
    required: ['task_id', 'status', 'stage'],
    title: 'PositionAnalysisReportResponse'
} as const;

export const PositionAnalysisSnapshotResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        source_sheet: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Sheet'
        },
        filters_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Filters Json'
        },
        snapshot_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Snapshot Json'
        },
        selected_position_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Selected Position Ids'
        },
        visible_columns: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Visible Columns'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'title'],
    title: 'PositionAnalysisSnapshotResponse'
} as const;

export const PositionAnalysisTaskCreateRequestSchema = {
    properties: {
        snapshot: {
            additionalProperties: true,
            type: 'object',
            title: 'Snapshot'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        source_sheet: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Sheet'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'PositionAnalysisTaskCreateRequest'
} as const;

export const PositionAnalysisTaskResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        snapshot_id: {
            type: 'string',
            format: 'uuid',
            title: 'Snapshot Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        stage: {
            type: 'string',
            title: 'Stage'
        },
        input_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Input Json'
        },
        output_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Output Json'
        },
        report_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Report Text'
        },
        trace_json: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Trace Json'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'snapshot_id', 'user_id', 'status', 'stage'],
    title: 'PositionAnalysisTaskResponse'
} as const;

export const PositionAnalysisTaskRunResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        snapshot_id: {
            type: 'string',
            format: 'uuid',
            title: 'Snapshot Id'
        },
        task: {
            '$ref': '#/components/schemas/PositionAnalysisTaskResponse'
        },
        snapshot: {
            '$ref': '#/components/schemas/PositionAnalysisSnapshotResponse'
        },
        report: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Report'
        },
        trace: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Trace'
        }
    },
    type: 'object',
    required: ['status', 'task_id', 'snapshot_id', 'task', 'snapshot'],
    title: 'PositionAnalysisTaskRunResponse'
} as const;

export const PositionAnalysisTraceResponseSchema = {
    properties: {
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        stage: {
            type: 'string',
            title: 'Stage'
        },
        trace: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Trace'
        }
    },
    type: 'object',
    required: ['task_id', 'status', 'stage'],
    title: 'PositionAnalysisTraceResponse'
} as const;

export const PositionAnalyzeRecordSchema = {
    properties: {
        position_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Id'
        },
        department_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Name'
        },
        office_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Office Name'
        },
        job_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Title'
        },
        position_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Code'
        },
        work_location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Work Location'
        },
        household_registration_location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Household Registration Location'
        },
        education_requirement: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Education Requirement'
        },
        degree_requirement: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Degree Requirement'
        },
        major_requirement: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Major Requirement'
        },
        political_status_requirement: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Political Status Requirement'
        },
        grassroots_years_requirement: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grassroots Years Requirement'
        },
        recruit_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recruit Count'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        department_website: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Website'
        },
        contact_phone_1: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone 1'
        },
        contact_phone_2: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone 2'
        },
        contact_phone_3: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone 3'
        },
        score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Score'
        },
        recommend_level: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommend Level'
        },
        risk_level: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Level'
        },
        need_manual_confirm: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Need Manual Confirm'
        },
        reasons: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Reasons'
        },
        risks: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Risks'
        }
    },
    type: 'object',
    title: 'PositionAnalyzeRecord'
} as const;

export const PositionAnalyzeRequestSchema = {
    properties: {
        position_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Position Ids'
        },
        query: {
            type: 'string',
            title: 'Query',
            default: ''
        },
        top_k: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Top K',
            default: 10
        },
        position_profile: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PositionRecommendationProfile'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'PositionAnalyzeRequest'
} as const;

export const PositionAnalyzeResponseSchema = {
    properties: {
        analysis: {
            type: 'string',
            title: 'Analysis'
        },
        summary: {
            additionalProperties: true,
            type: 'object',
            title: 'Summary'
        },
        recommendations: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Recommendations'
        },
        selected_positions: {
            items: {
                '$ref': '#/components/schemas/PositionAnalyzeRecord'
            },
            type: 'array',
            title: 'Selected Positions'
        },
        retrieval_trace: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Retrieval Trace'
        }
    },
    type: 'object',
    required: ['analysis'],
    title: 'PositionAnalyzeResponse'
} as const;

export const PositionListItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        department_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Code'
        },
        department_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Name'
        },
        office_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Office Name'
        },
        institution_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Institution Type'
        },
        job_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Title'
        },
        position_attribute: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Attribute'
        },
        position_distribution: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Distribution'
        },
        position_desc: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Desc'
        },
        position_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Code'
        },
        institution_level: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Institution Level'
        },
        exam_category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Exam Category'
        },
        recruit_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recruit Count'
        },
        major_requirement: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Major Requirement'
        },
        education_requirement: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Education Requirement'
        },
        degree_requirement: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Degree Requirement'
        },
        political_status_requirement: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Political Status Requirement'
        },
        grassroots_years_requirement: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grassroots Years Requirement'
        },
        grassroots_project_experience: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grassroots Project Experience'
        },
        professional_test_in_interview: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Professional Test In Interview'
        },
        interview_ratio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Interview Ratio'
        },
        work_location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Work Location'
        },
        household_registration_location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Household Registration Location'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        department_website: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Website'
        },
        contact_phone_1: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone 1'
        },
        contact_phone_2: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone 2'
        },
        contact_phone_3: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone 3'
        },
        source_file: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source File'
        },
        source_sheet: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Sheet'
        },
        source_row_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Row Number'
        },
        raw_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Raw Data'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'PositionListItem'
} as const;

export const PositionListResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PositionListItem'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        filters: {
            additionalProperties: true,
            type: 'object',
            title: 'Filters'
        }
    },
    type: 'object',
    required: ['data', 'count', 'page', 'page_size'],
    title: 'PositionListResponse'
} as const;

export const PositionPageSavedSnapshotSchema = {
    properties: {
        savedAt: {
            type: 'string',
            title: 'Savedat',
            default: ''
        },
        rowCount: {
            type: 'integer',
            title: 'Rowcount',
            default: 0
        },
        rowIds: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Rowids'
        },
        filters: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Filters'
        },
        sortKey: {
            type: 'string',
            title: 'Sortkey',
            default: 'source_row_number'
        },
        sortDirection: {
            type: 'string',
            enum: ['asc', 'desc'],
            title: 'Sortdirection',
            default: 'asc'
        }
    },
    type: 'object',
    title: 'PositionPageSavedSnapshot'
} as const;

export const PositionPageSheetStateSchema = {
    properties: {
        filters: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Filters'
        },
        sortKey: {
            type: 'string',
            title: 'Sortkey',
            default: 'source_row_number'
        },
        sortDirection: {
            type: 'string',
            enum: ['asc', 'desc'],
            title: 'Sortdirection',
            default: 'asc'
        },
        scrollTop: {
            type: 'integer',
            title: 'Scrolltop',
            default: 0
        },
        scrollLeft: {
            type: 'integer',
            title: 'Scrollleft',
            default: 0
        }
    },
    type: 'object',
    title: 'PositionPageSheetState'
} as const;

export const PositionPageStateSchema = {
    properties: {
        activeSheet: {
            type: 'string',
            title: 'Activesheet'
        },
        sheets: {
            additionalProperties: {
                '$ref': '#/components/schemas/PositionPageSheetState'
            },
            type: 'object',
            title: 'Sheets'
        },
        savedSnapshots: {
            additionalProperties: {
                '$ref': '#/components/schemas/PositionPageSavedSnapshot'
            },
            type: 'object',
            title: 'Savedsnapshots'
        }
    },
    type: 'object',
    required: ['activeSheet', 'sheets'],
    title: 'PositionPageState'
} as const;

export const PositionRecommendationProfileSchema = {
    properties: {
        major: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Major'
        },
        education: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Education'
        },
        degree: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Degree'
        },
        political_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Political Status'
        },
        is_fresh_graduate: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Fresh Graduate'
        },
        grassroots_experience_years: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grassroots Experience Years'
        },
        target_regions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Target Regions'
        },
        avoid_conditions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Avoid Conditions'
        },
        desired_departments: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Desired Departments'
        },
        desired_positions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Desired Positions'
        },
        excluded_positions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Excluded Positions'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'PositionRecommendationProfile'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TextToSpeechRequestSchema = {
    properties: {
        text: {
            type: 'string',
            title: 'Text'
        },
        voice: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Voice'
        },
        hard_filter_passed: {
            type: 'boolean',
            title: 'Hard Filter Passed',
            default: false
        },
        hard_filter_reasons: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Hard Filter Reasons'
        },
        hard_filter_risks: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Hard Filter Risks'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'TextToSpeechRequest'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserProfileResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        education: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Education'
        },
        degree: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Degree'
        },
        major: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Major'
        },
        political_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Political Status'
        },
        is_fresh_graduate: {
            type: 'boolean',
            title: 'Is Fresh Graduate',
            default: false
        },
        grassroots_experience_years: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grassroots Experience Years'
        },
        target_regions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Target Regions'
        },
        avoid_conditions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Avoid Conditions'
        },
        desired_departments: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Desired Departments'
        },
        desired_positions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Desired Positions'
        },
        excluded_positions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Excluded Positions'
        },
        daily_study_hours: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Daily Study Hours'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['id', 'user_id'],
    title: 'UserProfileResponse'
} as const;

export const UserProfileUpdateRequestSchema = {
    properties: {
        education: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Education'
        },
        degree: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Degree'
        },
        major: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Major'
        },
        political_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Political Status'
        },
        is_fresh_graduate: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Fresh Graduate'
        },
        grassroots_experience_years: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grassroots Experience Years'
        },
        target_regions: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Regions'
        },
        avoid_conditions: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avoid Conditions'
        },
        desired_departments: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Desired Departments'
        },
        desired_positions: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Desired Positions'
        },
        excluded_positions: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excluded Positions'
        },
        daily_study_hours: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Daily Study Hours'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'UserProfileUpdateRequest'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;