// This file is auto-generated by @hey-api/openapi-ts

export type Body_gwy_upload_chat_attachments = {
    files: Array<((Blob | File))>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatAttachmentListResponse = {
    data: Array<ChatAttachmentResponse>;
    count: number;
};

export type ChatAttachmentResponse = {
    id: string;
    session_id: string;
    file_name: string;
    original_name: string;
    attachment_type: string;
    mime_type: string;
    file_path: string;
    size_bytes: number;
    summary?: (string | null);
    extracted_text?: (string | null);
    extraction_status: string;
    metadata_json?: {
        [key: string]: unknown;
    };
    created_at?: (string | null);
};

export type ChatMessageListResponse = {
    data: Array<ChatMessageResponse>;
    count: number;
};

export type ChatMessageResponse = {
    id: string;
    session_id: string;
    role: string;
    content: string;
    intent?: (string | null);
    historical_reference?: boolean;
    citations?: Array<{
        [key: string]: unknown;
    }>;
    retrieval_trace?: Array<{
        [key: string]: unknown;
    }>;
    metadata_json?: {
        [key: string]: unknown;
    };
    created_at?: (string | null);
};

export type ChatRequestBase = {
    query: string;
    year?: number;
    exam_type?: string;
    doc_group?: (string | null);
    doc_type?: (string | null);
    top_k?: number;
    use_rerank?: boolean;
    mode?: ('policy_rag' | 'position_recommendation' | null);
    intent_hint?: (string | null);
    position_profile?: (PositionRecommendationProfile | null);
};

export type ChatSessionCreateRequest = {
    title?: (string | null);
};

export type ChatSessionListResponse = {
    data: Array<ChatSessionResponse>;
    count: number;
};

export type ChatSessionResponse = {
    id: string;
    title: string;
    last_intent?: (string | null);
    active_topic?: (string | null);
    mentioned_docs?: Array<(string)>;
    summary?: (string | null);
    summary_updated_at?: (string | null);
    created_at?: (string | null);
};

export type ChunkDebugListResponse = {
    data: Array<ChunkDebugRecord>;
    count: number;
};

export type ChunkDebugRecord = {
    chunk_id: string;
    source_file: string;
    doc_group: string;
    doc_type: string;
    chunk_type: string;
    section: string;
    question: string;
    page_start: number;
    page_end: number;
    char_count: number;
    content: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type ChunkDebugStatsResponse = {
    source_file?: (string | null);
    doc_group?: (string | null);
    doc_type?: (string | null);
    total_chunks: number;
    chunk_type_count: {
        [key: string]: (number);
    };
    avg_char_count: number;
    min_char_count: number;
    max_char_count: number;
    missing_question_count: number;
    missing_section_count: number;
    missing_page_count: number;
    fallback_count?: number;
    fallback_ratio: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PolicyImportRequest = {
    path: string;
    owner_user_id?: (string | null);
    collection_name?: (string | null);
};

export type PolicyImportResponse = {
    success: boolean;
    file_count: number;
    chunk_count: number;
    failed_files: Array<(string)>;
    chunk_stats?: ({
    [key: string]: unknown;
} | null);
    warnings?: Array<(string)>;
    debug_artifacts?: {
        [key: string]: (string | null);
    };
    layout_stats?: ({
    [key: string]: unknown;
} | null);
};

export type PolicyQueryRequest = {
    query: string;
    session_id?: (string | null);
    year?: number;
    exam_type?: string;
    doc_group?: (string | null);
    doc_type?: (string | null);
    top_k?: number;
    use_rerank?: boolean;
    mode?: ('policy_rag' | 'position_recommendation' | null);
    intent_hint?: (string | null);
    position_profile?: (PositionRecommendationProfile | null);
};

export type PolicyQueryResponse = {
    answer: string;
    intent: string;
    need_rag: boolean;
    decision_branch?: (string | null);
    citations: Array<{
        [key: string]: unknown;
    }>;
    retrieval_trace: Array<{
        [key: string]: unknown;
    }>;
    rewritten_queries: Array<(string)>;
    metadata_filter?: (string | null);
    rerank_results: Array<{
        [key: string]: unknown;
    }>;
    recommendations?: Array<{
        [key: string]: unknown;
    }>;
    risk_review?: {
        [key: string]: unknown;
    };
    report?: (string | null);
    need_more_info?: boolean;
    missing_fields?: Array<(string)>;
    recommendation_task_id?: (string | null);
    historical_reference?: boolean;
    session?: (ChatSessionResponse | null);
    user_message?: (ChatMessageResponse | null);
    assistant_message?: (ChatMessageResponse | null);
};

export type PolicySearchRequest = {
    query: string;
    year?: (number | null);
    exam_type?: (string | null);
    doc_group?: (string | null);
    top_k?: number;
    use_rerank?: boolean;
};

export type PolicySearchResponse = {
    results: Array<PolicySearchResult>;
};

export type PolicySearchResult = {
    content: string;
    score: number;
    rerank_score?: (number | null);
    metadata?: {
        [key: string]: unknown;
    };
};

export type PositionAnalysisReportResponse = {
    task_id: string;
    status: string;
    stage: string;
    report?: (string | null);
    report_text?: (string | null);
};

export type PositionAnalysisSnapshotResponse = {
    id: string;
    user_id: string;
    title: string;
    source_sheet?: (string | null);
    filters_json?: {
        [key: string]: unknown;
    };
    snapshot_json?: {
        [key: string]: unknown;
    };
    selected_position_ids?: Array<(string)>;
    visible_columns?: Array<(string)>;
    notes?: (string | null);
    created_at?: (string | null);
};

export type PositionAnalysisTaskCreateRequest = {
    snapshot?: {
        [key: string]: unknown;
    };
    title?: (string | null);
    source_sheet?: (string | null);
    notes?: (string | null);
};

export type PositionAnalysisTaskResponse = {
    id: string;
    snapshot_id: string;
    user_id: string;
    status: string;
    stage: string;
    input_json?: {
        [key: string]: unknown;
    };
    output_json?: {
        [key: string]: unknown;
    };
    report_text?: (string | null);
    trace_json?: Array<{
        [key: string]: unknown;
    }>;
    error_message?: (string | null);
    started_at?: (string | null);
    finished_at?: (string | null);
    created_at?: (string | null);
};

export type PositionAnalysisTaskRunResponse = {
    status: string;
    task_id: string;
    snapshot_id: string;
    task: PositionAnalysisTaskResponse;
    snapshot: PositionAnalysisSnapshotResponse;
    report?: (string | null);
    trace?: Array<{
        [key: string]: unknown;
    }>;
};

export type PositionAnalysisTraceResponse = {
    task_id: string;
    status: string;
    stage: string;
    trace?: Array<{
        [key: string]: unknown;
    }>;
};

export type PositionAnalyzeRecord = {
    position_id?: (string | null);
    department_name?: (string | null);
    office_name?: (string | null);
    job_title?: (string | null);
    position_code?: (string | null);
    work_location?: (string | null);
    household_registration_location?: (string | null);
    education_requirement?: (string | null);
    degree_requirement?: (string | null);
    major_requirement?: (string | null);
    political_status_requirement?: (string | null);
    grassroots_years_requirement?: (string | null);
    recruit_count?: (number | null);
    remarks?: (string | null);
    department_website?: (string | null);
    contact_phone_1?: (string | null);
    contact_phone_2?: (string | null);
    contact_phone_3?: (string | null);
    score?: (number | null);
    recommend_level?: (string | null);
    risk_level?: (string | null);
    need_manual_confirm?: (boolean | null);
    reasons?: Array<{
        [key: string]: unknown;
    }>;
    risks?: Array<{
        [key: string]: unknown;
    }>;
};

export type PositionAnalyzeRequest = {
    position_ids?: Array<(string)>;
    query?: string;
    top_k?: number;
    position_profile?: (PositionRecommendationProfile | null);
};

export type PositionAnalyzeResponse = {
    analysis: string;
    summary?: {
        [key: string]: unknown;
    };
    recommendations?: Array<{
        [key: string]: unknown;
    }>;
    selected_positions?: Array<PositionAnalyzeRecord>;
    retrieval_trace?: Array<{
        [key: string]: unknown;
    }>;
};

export type PositionListItem = {
    id: string;
    department_code?: (string | null);
    department_name?: (string | null);
    office_name?: (string | null);
    institution_type?: (string | null);
    job_title?: (string | null);
    position_attribute?: (string | null);
    position_distribution?: (string | null);
    position_desc?: (string | null);
    position_code?: (string | null);
    institution_level?: (string | null);
    exam_category?: (string | null);
    recruit_count?: (number | null);
    major_requirement?: (string | null);
    education_requirement?: (string | null);
    degree_requirement?: (string | null);
    political_status_requirement?: (string | null);
    grassroots_years_requirement?: (string | null);
    grassroots_project_experience?: (string | null);
    professional_test_in_interview?: (string | null);
    interview_ratio?: (string | null);
    work_location?: (string | null);
    household_registration_location?: (string | null);
    remarks?: (string | null);
    department_website?: (string | null);
    contact_phone_1?: (string | null);
    contact_phone_2?: (string | null);
    contact_phone_3?: (string | null);
    source_file?: (string | null);
    source_sheet?: (string | null);
    source_row_number?: (number | null);
    raw_data?: {
        [key: string]: unknown;
    };
};

export type PositionListResponse = {
    data: Array<PositionListItem>;
    count: number;
    page: number;
    page_size: number;
    filters?: {
        [key: string]: unknown;
    };
};

export type PositionPageSavedSnapshot = {
    savedAt?: string;
    rowCount?: number;
    rowIds?: Array<(string)>;
    filters?: {
        [key: string]: (string);
    };
    sortKey?: string;
    sortDirection?: 'asc' | 'desc';
};

export type sortDirection = 'asc' | 'desc';

export type PositionPageSheetState = {
    filters?: {
        [key: string]: (string);
    };
    sortKey?: string;
    sortDirection?: 'asc' | 'desc';
    scrollTop?: number;
    scrollLeft?: number;
};

export type PositionPageState = {
    activeSheet: string;
    sheets: {
        [key: string]: PositionPageSheetState;
    };
    savedSnapshots?: {
        [key: string]: PositionPageSavedSnapshot;
    };
};

export type PositionRecommendationProfile = {
    major?: (string | null);
    education?: (string | null);
    degree?: (string | null);
    political_status?: (string | null);
    is_fresh_graduate?: (boolean | null);
    grassroots_experience_years?: (number | null);
    target_regions?: Array<(string)>;
    avoid_conditions?: Array<(string)>;
    desired_departments?: Array<(string)>;
    desired_positions?: Array<(string)>;
    excluded_positions?: Array<(string)>;
    notes?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TextToSpeechRequest = {
    text: string;
    voice?: (string | null);
    hard_filter_passed?: boolean;
    hard_filter_reasons?: Array<(string)>;
    hard_filter_risks?: Array<(string)>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserProfileResponse = {
    id: string;
    user_id: string;
    education?: (string | null);
    degree?: (string | null);
    major?: (string | null);
    political_status?: (string | null);
    is_fresh_graduate?: boolean;
    grassroots_experience_years?: (number | null);
    target_regions?: Array<(string)>;
    avoid_conditions?: Array<(string)>;
    desired_departments?: Array<(string)>;
    desired_positions?: Array<(string)>;
    excluded_positions?: Array<(string)>;
    daily_study_hours?: (number | null);
    notes?: (string | null);
};

export type UserProfileUpdateRequest = {
    education?: (string | null);
    degree?: (string | null);
    major?: (string | null);
    political_status?: (string | null);
    is_fresh_graduate?: (boolean | null);
    grassroots_experience_years?: (number | null);
    target_regions?: (Array<(string)> | null);
    avoid_conditions?: (Array<(string)> | null);
    desired_departments?: (Array<(string)> | null);
    desired_positions?: (Array<(string)> | null);
    excluded_positions?: (Array<(string)> | null);
    daily_study_hours?: (number | null);
    notes?: (string | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type GwyHealthCheckResponse = (Message);

export type GwyImportPolicyPdfsData = {
    requestBody: PolicyImportRequest;
};

export type GwyImportPolicyPdfsResponse = (PolicyImportResponse);

export type GwyListChunkDebugsData = {
    limit?: number;
    offset?: number;
    sourceFile?: (string | null);
};

export type GwyListChunkDebugsResponse = (ChunkDebugListResponse);

export type GwyGetChunkDebugData = {
    chunkId: string;
};

export type GwyGetChunkDebugResponse = (ChunkDebugRecord);

export type GwyGetChunkDebugStatsData = {
    sourceFile?: (string | null);
};

export type GwyGetChunkDebugStatsResponse = (ChunkDebugStatsResponse);

export type GwyListPositionsData = {
    degree?: (string | null);
    department?: (string | null);
    education?: (string | null);
    jobTitle?: (string | null);
    major?: (string | null);
    page?: number;
    pageSize?: number;
    politicalStatus?: (string | null);
    region?: (string | null);
    year?: number;
};

export type GwyListPositionsResponse = (PositionListResponse);

export type GwyListPositionsGridData = {
    degree?: (string | null);
    department?: (string | null);
    education?: (string | null);
    jobTitle?: (string | null);
    major?: (string | null);
    politicalStatus?: (string | null);
    region?: (string | null);
    year?: (number | null);
};

export type GwyListPositionsGridResponse = (PositionListResponse);

export type GwyAnalyzePositionsData = {
    requestBody: PositionAnalyzeRequest;
};

export type GwyAnalyzePositionsResponse = (PositionAnalyzeResponse);

export type GwyGetPositionPageStateResponse = (PositionPageState);

export type GwySavePositionPageStateData = {
    requestBody: PositionPageState;
};

export type GwySavePositionPageStateResponse = (PositionPageState);

export type GwyClearPositionPageStateResponse = ({
    [key: string]: (boolean);
});

export type GwySearchPolicyData = {
    requestBody: PolicySearchRequest;
};

export type GwySearchPolicyResponse = (PolicySearchResponse);

export type GwyQueryPolicyData = {
    requestBody: PolicyQueryRequest;
};

export type GwyQueryPolicyResponse = (PolicyQueryResponse);

export type GwyListChatSessionsResponse = (ChatSessionListResponse);

export type GwyCreateChatSessionData = {
    requestBody: ChatSessionCreateRequest;
};

export type GwyCreateChatSessionResponse = (ChatSessionResponse);

export type GwyDeleteChatSessionData = {
    sessionId: string;
};

export type GwyDeleteChatSessionResponse = (Message);

export type GwyGetMyProfileResponse = (UserProfileResponse);

export type GwyUpdateMyProfileData = {
    requestBody: UserProfileUpdateRequest;
};

export type GwyUpdateMyProfileResponse = (UserProfileResponse);

export type GwyListChatMessagesData = {
    sessionId: string;
};

export type GwyListChatMessagesResponse = (ChatMessageListResponse);

export type GwyCreateChatMessageData = {
    requestBody: ChatRequestBase;
    sessionId: string;
};

export type GwyCreateChatMessageResponse = (PolicyQueryResponse);

export type GwyCreateChatMessageStreamData = {
    requestBody: ChatRequestBase;
    sessionId: string;
};

export type GwyCreateChatMessageStreamResponse = (unknown);

export type GwyCreateAudioSpeechData = {
    requestBody: TextToSpeechRequest;
};

export type GwyCreateAudioSpeechResponse = (unknown);

export type GwyListChatAttachmentsData = {
    sessionId: string;
};

export type GwyListChatAttachmentsResponse = (ChatAttachmentListResponse);

export type GwyUploadChatAttachmentsData = {
    formData: Body_gwy_upload_chat_attachments;
    sessionId: string;
};

export type GwyUploadChatAttachmentsResponse = (ChatAttachmentListResponse);

export type GwyDeleteChatAttachmentData = {
    attachmentId: string;
    sessionId: string;
};

export type GwyDeleteChatAttachmentResponse = (Message);

export type GwyAnalysisCreatePositionAnalysisTaskData = {
    requestBody: PositionAnalysisTaskCreateRequest;
};

export type GwyAnalysisCreatePositionAnalysisTaskResponse = (PositionAnalysisTaskRunResponse);

export type GwyAnalysisGetPositionAnalysisTaskData = {
    taskId: string;
};

export type GwyAnalysisGetPositionAnalysisTaskResponse = (PositionAnalysisTaskResponse);

export type GwyAnalysisGetPositionAnalysisTaskTraceData = {
    taskId: string;
};

export type GwyAnalysisGetPositionAnalysisTaskTraceResponse = (PositionAnalysisTraceResponse);

export type GwyAnalysisGetPositionAnalysisTaskReportData = {
    taskId: string;
};

export type GwyAnalysisGetPositionAnalysisTaskReportResponse = (PositionAnalysisReportResponse);

export type GwyAnalysisGetPositionAnalysisSnapshotData = {
    snapshotId: string;
};

export type GwyAnalysisGetPositionAnalysisSnapshotResponse = (PositionAnalysisSnapshotResponse);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);