"""add gwy tables

Revision ID: c3f6adfcebb2
Revises: fe56fa70289e
Create Date: 2026-05-27 16:46:34.807240

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c3f6adfcebb2'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gwy_experience_memory',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('scenario', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('lesson', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_experience_memory_agent_name'), 'gwy_experience_memory', ['agent_name'], unique=False)
    op.create_index(op.f('ix_gwy_experience_memory_scenario'), 'gwy_experience_memory', ['scenario'], unique=False)
    op.create_table('gwy_position',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('office_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('institution_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('position_attribute', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('position_distribution', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('position_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('institution_level', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('exam_category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('recruit_count', sa.Integer(), nullable=True),
    sa.Column('major_requirement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('education_requirement', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('degree_requirement', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('political_status_requirement', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('grassroots_years_requirement', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('grassroots_project_experience', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('professional_test_in_interview', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('interview_ratio', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('work_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('household_registration_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('department_website', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('contact_phone_1', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('contact_phone_2', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('contact_phone_3', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('source_file', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('source_sheet', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_position_department_code'), 'gwy_position', ['department_code'], unique=False)
    op.create_index(op.f('ix_gwy_position_department_name'), 'gwy_position', ['department_name'], unique=False)
    op.create_index(op.f('ix_gwy_position_job_title'), 'gwy_position', ['job_title'], unique=False)
    op.create_index(op.f('ix_gwy_position_position_code'), 'gwy_position', ['position_code'], unique=False)
    op.create_index(op.f('ix_gwy_position_source_file'), 'gwy_position', ['source_file'], unique=False)
    op.create_index(op.f('ix_gwy_position_source_sheet'), 'gwy_position', ['source_sheet'], unique=False)
    op.create_table('gwy_conversation_memory',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('memory_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('memory_value', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_conversation_memory_conversation_id'), 'gwy_conversation_memory', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_gwy_conversation_memory_expires_at'), 'gwy_conversation_memory', ['expires_at'], unique=False)
    op.create_index(op.f('ix_gwy_conversation_memory_memory_key'), 'gwy_conversation_memory', ['memory_key'], unique=False)
    op.create_index(op.f('ix_gwy_conversation_memory_user_id'), 'gwy_conversation_memory', ['user_id'], unique=False)
    op.create_table('gwy_decision_memory',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('position_id', sa.Uuid(), nullable=True),
    sa.Column('decision_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('decision_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['gwy_position.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_decision_memory_decision_type'), 'gwy_decision_memory', ['decision_type'], unique=False)
    op.create_index(op.f('ix_gwy_decision_memory_user_id'), 'gwy_decision_memory', ['user_id'], unique=False)
    op.create_table('gwy_recommendation_task',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('exam_year', sa.Integer(), nullable=True),
    sa.Column('exam_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('target_regions', sa.JSON(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_recommendation_task_exam_type'), 'gwy_recommendation_task', ['exam_type'], unique=False)
    op.create_index(op.f('ix_gwy_recommendation_task_exam_year'), 'gwy_recommendation_task', ['exam_year'], unique=False)
    op.create_index(op.f('ix_gwy_recommendation_task_status'), 'gwy_recommendation_task', ['status'], unique=False)
    op.create_index(op.f('ix_gwy_recommendation_task_user_id'), 'gwy_recommendation_task', ['user_id'], unique=False)
    op.create_table('gwy_user_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('education', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('degree', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('political_status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_fresh_graduate', sa.Boolean(), nullable=False),
    sa.Column('grassroots_experience_years', sa.Integer(), nullable=True),
    sa.Column('target_regions', sa.JSON(), nullable=False),
    sa.Column('avoid_conditions', sa.JSON(), nullable=False),
    sa.Column('desired_departments', sa.JSON(), nullable=False),
    sa.Column('desired_positions', sa.JSON(), nullable=False),
    sa.Column('excluded_positions', sa.JSON(), nullable=False),
    sa.Column('daily_study_hours', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_user_profile_user_id'), 'gwy_user_profile', ['user_id'], unique=True)
    op.create_table('gwy_agent_run',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('graph_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['gwy_recommendation_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_agent_run_graph_name'), 'gwy_agent_run', ['graph_name'], unique=False)
    op.create_index(op.f('ix_gwy_agent_run_status'), 'gwy_agent_run', ['status'], unique=False)
    op.create_index(op.f('ix_gwy_agent_run_task_id'), 'gwy_agent_run', ['task_id'], unique=False)
    op.create_table('gwy_human_review',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('position_id', sa.Uuid(), nullable=True),
    sa.Column('review_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('review_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decision_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['gwy_position.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['gwy_recommendation_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_human_review_review_type'), 'gwy_human_review', ['review_type'], unique=False)
    op.create_index(op.f('ix_gwy_human_review_status'), 'gwy_human_review', ['status'], unique=False)
    op.create_index(op.f('ix_gwy_human_review_task_id'), 'gwy_human_review', ['task_id'], unique=False)
    op.create_table('gwy_recommendation_item',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('recommend_level', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('competition_level', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('need_manual_confirm', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['gwy_position.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['gwy_recommendation_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_recommendation_item_position_id'), 'gwy_recommendation_item', ['position_id'], unique=False)
    op.create_index(op.f('ix_gwy_recommendation_item_rank'), 'gwy_recommendation_item', ['rank'], unique=False)
    op.create_index(op.f('ix_gwy_recommendation_item_risk_level'), 'gwy_recommendation_item', ['risk_level'], unique=False)
    op.create_index(op.f('ix_gwy_recommendation_item_task_id'), 'gwy_recommendation_item', ['task_id'], unique=False)
    op.create_table('gwy_risk_item',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=True),
    sa.Column('risk_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('evidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('suggestion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['gwy_position.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['gwy_recommendation_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_risk_item_risk_level'), 'gwy_risk_item', ['risk_level'], unique=False)
    op.create_index(op.f('ix_gwy_risk_item_risk_type'), 'gwy_risk_item', ['risk_type'], unique=False)
    op.create_index(op.f('ix_gwy_risk_item_task_id'), 'gwy_risk_item', ['task_id'], unique=False)
    op.create_table('gwy_agent_step',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['gwy_agent_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_agent_step_agent_run_id'), 'gwy_agent_step', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_gwy_agent_step_status'), 'gwy_agent_step', ['status'], unique=False)
    op.create_index(op.f('ix_gwy_agent_step_step_name'), 'gwy_agent_step', ['step_name'], unique=False)
    op.create_table('gwy_tool_call',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_step_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['agent_step_id'], ['gwy_agent_step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gwy_tool_call_agent_step_id'), 'gwy_tool_call', ['agent_step_id'], unique=False)
    op.create_index(op.f('ix_gwy_tool_call_status'), 'gwy_tool_call', ['status'], unique=False)
    op.create_index(op.f('ix_gwy_tool_call_tool_name'), 'gwy_tool_call', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gwy_tool_call_tool_name'), table_name='gwy_tool_call')
    op.drop_index(op.f('ix_gwy_tool_call_status'), table_name='gwy_tool_call')
    op.drop_index(op.f('ix_gwy_tool_call_agent_step_id'), table_name='gwy_tool_call')
    op.drop_table('gwy_tool_call')
    op.drop_index(op.f('ix_gwy_agent_step_step_name'), table_name='gwy_agent_step')
    op.drop_index(op.f('ix_gwy_agent_step_status'), table_name='gwy_agent_step')
    op.drop_index(op.f('ix_gwy_agent_step_agent_run_id'), table_name='gwy_agent_step')
    op.drop_table('gwy_agent_step')
    op.drop_index(op.f('ix_gwy_risk_item_task_id'), table_name='gwy_risk_item')
    op.drop_index(op.f('ix_gwy_risk_item_risk_type'), table_name='gwy_risk_item')
    op.drop_index(op.f('ix_gwy_risk_item_risk_level'), table_name='gwy_risk_item')
    op.drop_table('gwy_risk_item')
    op.drop_index(op.f('ix_gwy_recommendation_item_task_id'), table_name='gwy_recommendation_item')
    op.drop_index(op.f('ix_gwy_recommendation_item_risk_level'), table_name='gwy_recommendation_item')
    op.drop_index(op.f('ix_gwy_recommendation_item_rank'), table_name='gwy_recommendation_item')
    op.drop_index(op.f('ix_gwy_recommendation_item_position_id'), table_name='gwy_recommendation_item')
    op.drop_table('gwy_recommendation_item')
    op.drop_index(op.f('ix_gwy_human_review_task_id'), table_name='gwy_human_review')
    op.drop_index(op.f('ix_gwy_human_review_status'), table_name='gwy_human_review')
    op.drop_index(op.f('ix_gwy_human_review_review_type'), table_name='gwy_human_review')
    op.drop_table('gwy_human_review')
    op.drop_index(op.f('ix_gwy_agent_run_task_id'), table_name='gwy_agent_run')
    op.drop_index(op.f('ix_gwy_agent_run_status'), table_name='gwy_agent_run')
    op.drop_index(op.f('ix_gwy_agent_run_graph_name'), table_name='gwy_agent_run')
    op.drop_table('gwy_agent_run')
    op.drop_index(op.f('ix_gwy_user_profile_user_id'), table_name='gwy_user_profile')
    op.drop_table('gwy_user_profile')
    op.drop_index(op.f('ix_gwy_recommendation_task_user_id'), table_name='gwy_recommendation_task')
    op.drop_index(op.f('ix_gwy_recommendation_task_status'), table_name='gwy_recommendation_task')
    op.drop_index(op.f('ix_gwy_recommendation_task_exam_year'), table_name='gwy_recommendation_task')
    op.drop_index(op.f('ix_gwy_recommendation_task_exam_type'), table_name='gwy_recommendation_task')
    op.drop_table('gwy_recommendation_task')
    op.drop_index(op.f('ix_gwy_decision_memory_user_id'), table_name='gwy_decision_memory')
    op.drop_index(op.f('ix_gwy_decision_memory_decision_type'), table_name='gwy_decision_memory')
    op.drop_table('gwy_decision_memory')
    op.drop_index(op.f('ix_gwy_conversation_memory_user_id'), table_name='gwy_conversation_memory')
    op.drop_index(op.f('ix_gwy_conversation_memory_memory_key'), table_name='gwy_conversation_memory')
    op.drop_index(op.f('ix_gwy_conversation_memory_expires_at'), table_name='gwy_conversation_memory')
    op.drop_index(op.f('ix_gwy_conversation_memory_conversation_id'), table_name='gwy_conversation_memory')
    op.drop_table('gwy_conversation_memory')
    op.drop_index(op.f('ix_gwy_position_source_sheet'), table_name='gwy_position')
    op.drop_index(op.f('ix_gwy_position_source_file'), table_name='gwy_position')
    op.drop_index(op.f('ix_gwy_position_position_code'), table_name='gwy_position')
    op.drop_index(op.f('ix_gwy_position_job_title'), table_name='gwy_position')
    op.drop_index(op.f('ix_gwy_position_department_name'), table_name='gwy_position')
    op.drop_index(op.f('ix_gwy_position_department_code'), table_name='gwy_position')
    op.drop_table('gwy_position')
    op.drop_index(op.f('ix_gwy_experience_memory_scenario'), table_name='gwy_experience_memory')
    op.drop_index(op.f('ix_gwy_experience_memory_agent_name'), table_name='gwy_experience_memory')
    op.drop_table('gwy_experience_memory')
    # ### end Alembic commands ###
